config/routes.rb
Rails.application.routes.draw do
  
  get 'artwork_favorites/update'
  get 'orderartworks/index'
  get 'orderartworks/show'
  get 'orderartworks/new'
  get 'orderartworks/edit'
  
  resources :orders do 
    resources:orderitems
  end
  
  
  get 'cart/index'
  resources :artworks
  devise_for :artists
  
  devise_for :customers do
      resources:orders
      
    end
    
get '/checkout' => 'cart#createOrder'
    
    
  root 'static_pages#home'
  
  get '/aboutus' => 'static_pages#aboutus'
  
  get '/faq' => 'static_pages#faq'
  
  
 #root :to => 'site#home'
 
   get '/artist-account' => 'static_pages#artist-account'
   get '/customer-account' => 'static_pages#customer-account'
  
  
  #CART ROUTES
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart' =>'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  
  get '/paid/:id' => 'static_pages#paid'
  
  post '/search' => 'artworks#search'
  
  #  get 'static_pages/home'
 # get 'static_pages/aboutus'
  #get 'static_pages/faq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def aboutus
  end

  def faq
  end
  
  def paid
    
    @order = Order.find_by(id: params[:id])
    @order.update_attribute(:status, "Paid by User: #{current_customer.email}")
    
    
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/aboutus.html.erb
<% provide(:title, "About Us") %>
 <h1 class="w3-center">ABOUT US</h1>
 
 <div class="w3-row w3-padding-32 w3-section">
    <div class="w3-col m4 w3-container">
      
      <%= image_tag("aboutus.jpg", alt: "About Us", :class => "smallerImgs") %> 
    </div>
    <div class="w3-col m8 w3-panel">
       <p>Welcome to Artfox Online Art Gallery, where you can browse our wide variety of artworks on sale from an array
 of talented artists. We have many years experience in connecting artists with potential buyers of their quality works.</p>
    </div>
  </div>
 

app/views/static_pages/artist-account.html.erb
<% provide(:title, "Your Artist Account") %>

<h1 class="w3-center">Your account details:</h3>
<table id="customers">
    <tbody>
      <tr>
          <td>Your Email (Username): </td>
          <td><%= current_artist.email %></td>
      </tr>
      <tr>
          <td>Your Name: </td>
          <td><%= current_artist.a_name %></td>
      </tr>
      <tr>
          <td>Your Address: </td>
          <td><%= current_artist.a_address %></td>
      </tr>
      <tr>
          <td>Your Phone Number: </td>
          <td><%= current_artist.a_phonenumber %></td>
      </tr>
       <tr>
          <td>Your PayPal Email: </td>
          <td><%= current_artist.a_paypal %></td>
      </tr>
      
     </tbody>
     
</table>
<br/>

<center><%= link_to 'Edit Your Details',edit_artist_registration_path, :class => "w3-button w3-large w3-black w3-hover-yellow" %></center>

app/views/static_pages/customer-account.html.erb
<% provide(:title, "Your Customer Account") %>

<div class="w3-col m6 w3-center w3-padding-large">
  
  <h1 class="w3-center">Your Account Details:</h3>
<table id="customers">
    <tbody>
      <tr>
          <td>Your Email (Username): </td>
          <td><%= current_customer.email %></td>
      </tr>
        <tr>
          <td>Your Name: </td>
          <td><%= current_customer.c_name %></td>
      </tr>
      <tr>
          <td>Your Address: </td>
          <td><%= current_customer.address %></td>
      </tr>
      <tr>
          <td>Your Phone Number: </td>
          <td><%= current_customer.c_phonenumber %></td>
      </tr>
       <tr>
          <td>Your PayPal Email: </td>
          <td><%= current_customer.c_paypal %></td>
      </tr>
      
     </tbody>
     
</table>

<br/>

<center><%= link_to 'Edit Your Details',edit_customer_registration_path,
:class => "w3-button w3-large w3-black w3-hover-yellow" %></center>
  
</div>

<div class="w3-col m6 w3-center w3-padding-large">
  
  


<h1 class="w3-center">Your Favourite Artworks:</h3>

<% current_customer.favorites.each do |favorite| %>

<div class="w3-col m4 w3-panel">
<%= image_tag(favorite.artwork.artpic, :class => "itemholsIm") if favorite.artwork.artpic.attached? %><br/>
<center><%= link_to favorite.artwork.title, favorite.artwork %></center>
</div>
<% end %>

<% if current_customer.favorites.empty? %>
Please add some favourites!
<% end %>
  
  
</div>

app/views/static_pages/faq.html.erb
<% provide(:title, "Frequently Asked Questions") %>

 <h1 class="w3-center">FREQUENTLY ASKED QUESTIONS</h1>
 
 <div class="w3-row w3-padding-32 w3-section">
     
     <button class="accordion">Is Postage Included in Prices?</button>
<div class="panel">
  <p>NO. Postage costs €50 flat rate for all orders, however if total of order is over €700 then shipping is free</p>
</div>

<button class="accordion">Can I order more than one artwork from different artists in the same order?</button>
<div class="panel">
  <p>YES. You can order as many different artists artworks as you wish in one order. The subtotal is paid into a holding PayPal
  account whereupon later this total is divided between the artists.</p>
</div>

<button class="accordion">Can I buy and sell art from one account?</button>
<div class="panel">
  <p>NO. You must sign up for separate buyer or seller accounts.</p>
</div>
<button class="accordion">What about refunds?</button>
<div class="panel">
  <p>If you are not happy with a purchase, you may contact the artist directly to arrange details. On each artworks page,
  there is a link underneath to contact the artist.</p>
</div>
     
     
 </div>
 
 <script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    }
  });
}

 </script>

app/views/static_pages/home.html.erb
<% provide(:title, "Homepage") %>

<div class="w3-row">
    
    <h2 class="w3-left">
            WELCOME TO ARTFOX!
        </h2>
    
    <p class="w3-left">Thank you for visiting our online art gallery website. We hope you enjoy your stay, and find some art that interests you.
        You can either sign up for Artist Seller or Customer Buyer accounts using the links on this page below, or from the menu links above.
        In this online store you can find an array of interesting artworks such as sculptures, paintings, printmaking and ceramics.</p>
    
    
   
    
</div>


<% if artist_signed_in? || customer_signed_in? %>

<% else %>

<hr class="home" id="homepanel">

<div class="homeboxes1 w3-col m6 w3-center w3-padding-large">
    <h2>Artist?</h3>
    <br><br>
    <a href="/artists/sign_up" class="w3-bar-item w3-button w3-yellow w3-hover-black">Sign up here</a><br><br>
    <a href="/artists/sign_in" class="w3-bar-item w3-button w3-yellow w3-hover-black">Login here</a>
</div>
<div class="homeboxes2 w3-col m6 w3-center w3-padding-large">
    <h2>Customer?</h3>
    <br><br>
    <a href="/customers/sign_up" class="w3-bar-item w3-button w3-yellow w3-hover-black">Sign up here</a><br><br>
    <a href="/customers/sign_in" class="w3-bar-item w3-button w3-yellow w3-hover-black">Login here</a>
</div>


<% end %>

app/views/static_pages/paid.html.erb
<div class="w3-content w3-container w3-padding-64">
    <h1 class="w3-center">THANK YOU VERY MUCH!</h1>
    
    <center>We will dispatch your order ASAP!</center><br/><br/>
    
    <center><a href="/" class="w3-button w3-large w3-black w3-hover-deep-orange">Back to Homepage</a></center>
    
</div>

app/views/static_pages/thanks.html.erb
<div class="w3-content w3-container w3-padding-64">
    <h1 class="w3-center">THANK YOU VERY MUCH!</h1>
    
    <center>We will dispatch your order ASAP!</center><br/><br/>
    
    <center><a href="/" class="w3-button w3-large w3-black w3-hover-deep-orange">Back to Homepage</a></center>
    
</div>