config/routes.rb
Rails.application.routes.draw do
  
  get 'artwork_favorites/update'
  get 'orderartworks/index'
  get 'orderartworks/show'
  get 'orderartworks/new'
  get 'orderartworks/edit'
  
  resources :orders do 
    resources:orderitems
  end
  
  
  get 'cart/index'
  resources :artworks
  devise_for :artists
  
  devise_for :customers do
      resources:orders
      
    end
    
get '/checkout' => 'cart#createOrder'
    
    
  root 'static_pages#home'
  
  get '/aboutus' => 'static_pages#aboutus'
  
  get '/faq' => 'static_pages#faq'
  
  
 #root :to => 'site#home'
 
   get '/artist-account' => 'static_pages#artist-account'
   get '/customer-account' => 'static_pages#customer-account'
  
  
  #CART ROUTES
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart' =>'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  
  get '/paid/:id' => 'static_pages#paid'
  
  post '/search' => 'artworks#search'
  
  #  get 'static_pages/home'
 # get 'static_pages/aboutus'
  #get 'static_pages/faq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :artist
  has_one_attached :artpic
  
 
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    #@artworks = Artwork.all
    
    if artist_signed_in?
    @artist = Artist.find(current_artist.id)
    @artworks = @artist.artworks.all
    else
      @artworks = Artwork.all
      #redirect_to :root #WHY DID I NEED TO COMMENT OUT THIS???
    end 
    
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  @favorite_exists = Favorite.where(artwork: @artwork, customer: current_customer) == [] ? false : true
   # @artist = Artist.find(current_artist.id)
 
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
    if artist_signed_in?
    @artist = Artist.find(current_artist.id)
  elsif customer_signed_in?
    @customer = Customer.find(current_customer.id)
    end
  end

  # POST /artworks
  # POST /artworks.json
  def create
  # @artwork = Artwork.new(artwork_params)
   @artwork = current_artist.artworks.new(artwork_params)
   
    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
   #artwork search
  
  def search
     st = "%#{params[:q]}%"
     @artworks = Artwork.where("desc like ?", st)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :cat, :desc, :price, :sold, :status, :artpic, :artist_id)
    end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_form.html.erb
 <% if artist_signed_in? %>

<center>

<%= form_with(model: artwork, local: true) do |form| %>
  <% if artwork.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h1>

      <ul>
      <% artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table id="customers">
    <tbody>
      <tr>
        <td><%= form.label "Artwork Title" %></td>
        <td><%= form.text_field :title, :size=>"50", :required => true  %></td>
      </tr>
      <tr>
        <td><%= form.label "Category" %></td>
        <td><%= form.text_field :cat, :required => true %></td>
      </tr>
      <tr>
        <td><%= form.label "Description" %></td>
        <td><%= form.text_area :desc, :size=>"50", :required => true %></td>
      </tr>
      <tr>
        <td><%= form.label "Price" %></td>
        <td><%= form.text_field :price, :size=>"6", :required => true  %></td>
      </tr>
      
      <tr>
        <td><%= form.label "Add a picture" %></td>
        <td><%= form.file_field :artpic %></td>
      </tr>
       <tr>
        <td colspan="2"><center><%= form.submit "Submit Details" %></center></td>
      </tr>
    </tbody>
    </table>
<div style="visibility: hidden;">
     
        <%= form.label "Status" %>
        <%= form.text_field :status, :size=>"6", :value=>"In Stock"  %>
      
      </div>

<% end %>

</center>

<% else %>
YOU DO NOT HAVE PERMISSION TO VIEW THIS PAGE<br><br>
<% end %>

app/views/artworks/edit.html.erb
<h1 class="w3-center">Edit Artwork Details</h1>

<% if artist_signed_in? %>

<% if @artwork.artist.email == @artist.email %>

<%= render 'form', artwork: @artwork %>

<% else %>
   
      <h1>You do not have permission to edit this artwork!</h1>
      
      <% end %>

<%= link_to 'Show', @artwork, :class => "w3-button w3-large w3-black w3-hover-yellow" %>
<%= link_to 'Back', artworks_path,:class => "w3-button w3-large w3-black w3-hover-yellow" %>

<% elsif customer_signed_in? %>
<p>Customer cant do this!</p>
<% else %>
<p>Unregistered user cant do this!</p>


<% end %>

app/views/artworks/index.html.erb
<% provide(:title, "ARTWORK CATALOGUE") %>

<p id="notice"><%= notice %></p>

<% if @artworks.empty? %>
<h1 class="w3-center">PORTFOLIO EMPTY! PLEASE ADD ARTWORKS</h1>
<% else %>
<h1 class="w3-center">BROWSE ARTWORKS</h1>
<% end %>


<% @artworks.each do |artwork| %>



<div class="w3-col m4 w3-panel">
        
        <%= image_tag(artwork.artpic, :class => "itemholsIm") if artwork.artpic.attached? %>

</div>

<div class="w3-col m8 w3-panel">
          <div class="myCols">
            <strong>"<%= artwork.title %>"</strong> | <%= artwork.cat %> | 
            Price: <%= number_to_currency(artwork.price, :unit => "€")  %> | 
            
            <% if artwork.status == "In Stock" %>
            <span class="statusGreen"><%= artwork.status %></span>
            <% else %>
            <span class="statusRed"><%= artwork.status %></span>
            <% end %>
            
            <br/>
            <p class="w3-left"><%= artwork.desc %></p>
            <p>
            <%= link_to 'Show More >>', artwork, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
        <% if artist_signed_in? && artwork.status == "In Stock" %>
        <%= link_to 'Edit', edit_artwork_path(artwork), :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
        <%= link_to 'Delete Artwork', artwork, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        
        
        </p>
      
                </div>
</div>
      
    <% end %>
    
    

<div class="bottomButtons">   
    
  <% if artist_signed_in? %>
    
       <%= link_to 'Add Artwork',  new_artwork_path, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
       
       <% end %>
    </div>

app/views/artworks/new.html.erb
<h1 class="w3-center">Create a new Artwork</h1>

<%= render 'form', artwork: @artwork, :class => "w3-button w3-large w3-black w3-hover-yellow" %>

<%= link_to 'Back', artworks_path, :class => "w3-button w3-large w3-black w3-hover-yellow" %>

app/views/artworks/search.html.erb
<% if @artworks.length == 0 %>

Nothing matches your search, try again!

<% end %>




<div class="w3-content w3-container w3-padding-64">
  
  <h1 class="w3-center">YOUR SEARCH RESULT(S) ARE...</h1>
  


    <% @artworks.each do |artwork| %>
    
    
      
      <div class="w3-col m4 w3-panel">
      
        <%= image_tag(artwork.artpic, :class => "itemholsIm") if artwork.artpic.attached? %>
        
        </div>
        
       <div class="w3-col m8 w3-panel">
          <div class="myCols">
            <strong>"<%= artwork.title %>"</strong> | <%= artwork.cat %> | 
            Price: <%= number_to_currency(artwork.price, :unit => "€")  %> | 
            
            <% if artwork.status == "In Stock" %>
            <span class="statusGreen"><%= artwork.status %></span>
            <% else %>
            <span class="statusRed"><%= artwork.status %></span>
            <% end %>
            
            <br/>
            <p class="w3-left"><%= artwork.desc %></p>
            <p>
            <%= link_to 'Show More >>', artwork, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
        <% if artist_signed_in? %>
        <%= link_to 'Edit', edit_artwork_path(artwork), :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
        <%= link_to 'Delete Artwork', artwork, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        
        
        </p>
      
                </div>
</div>
      
    <% end %>
    
    

<div class="bottomButtons">   
    
  <% if artist_signed_in? %>
    
       <%= link_to 'Add Artwork',  new_artwork_path, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %>
       
       <% end %>
    </div>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>


<p><%= link_to '<< Back to List of Artworks', artworks_path, :class => "w3-button w3-large w3-black w3-hover-yellow", :role => "button" %></p>

  <h1 class="w3-center"><%= @artwork.title %></h1>

<p>
<%= image_tag(@artwork.artpic, :class => "artworkBigger") if @artwork.artpic.attached? %>
</p>


<p>
  <strong>Artist: </strong><%= @artwork.artist.a_name %> | <strong>Art Category:</strong> <%= @artwork.cat %> | 
   <strong>Price: </strong><%= number_to_currency(@artwork.price, :unit => "€")  %> | 
   <% if @artwork.status == "In Stock" %>
            <span class="statusGreen"><%= @artwork.status %></span>
            <% else %>
            <span class="statusRed"><%= @artwork.status %></span>
            <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artwork.desc %>
</p>




<% if customer_signed_in? %>
<%= mail_to @artwork.artist.email, "CONTACT THE ARTIST!",:class => "w3-button w3-large w3-black w3-hover-yellow" %>

  <% if @artwork.status == "In Stock" %>
<a href="/cart/<%= @artwork.id %>" class="w3-button w3-large w3-black w3-hover-yellow">Add me to cart!</a>
<%= link_to favorite_text, artwork_favorites_update_path(artwork: @artwork), :class => "w3-button w3-large w3-black w3-hover-yellow", id:'favorite_link', remote: true %> 

  <% end %>

<br/><% end %>

<% if artist_signed_in? && @artwork.status == "In Stock" %>
<%= link_to 'Edit', edit_artwork_path(@artwork),:class => "w3-button w3-large w3-black w3-hover-yellow" %>  
<% end %>